[phases.build]
cmds = ["pnpm install --no-frozen-lockfile", "NODE_OPTIONS=--max-old-space-size=8192 pnpm run build"]

[phases.start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=8192"